# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HV5iS1bKiGQNtGp9vyGH9RZxl55uEhxq
"""

sfrom google.colab import drive
drive.mount('/content/drive')

import os, zipfile
zip_images = "/content/drive/MyDrive/new_projectS_dataset/ed_training.zip"
zip_masks  = "/content/drive/MyDrive/new_projectS_dataset/ed_training_gt.zip"
extract_images = "/content/images_raw"
extract_masks  = "/content/masks_raw"
os.makedirs(extract_images, exist_ok=True)
os.makedirs(extract_masks, exist_ok=True)
with zipfile.ZipFile(zip_images, 'r') as z:
    z.extractall(extract_images)
with zipfile.ZipFile(zip_masks, 'r') as z:
    z.extractall(extract_masks)

import os, shutil, glob
extract_images = "/content/images_raw"
extract_masks  = "/content/masks_raw"
final_dataset = "/content/drive/MyDrive/new_projectS_dataset/final_dataset"
os.makedirs(os.path.join(final_dataset, "images"), exist_ok=True)
os.makedirs(os.path.join(final_dataset, "masks"), exist_ok=True)
images = sorted([f for f in glob.glob(os.path.join(extract_images, "*")) if os.path.isfile(f)])
masks  = sorted([f for f in glob.glob(os.path.join(extract_masks, "*")) if os.path.isfile(f)])
images = images[:100]
masks  = masks[:100]
for i, (img, msk) in enumerate(zip(images, masks), 1):
    new_img_name = os.path.join(final_dataset, "images", f"case{i}_image.jpg")
    new_msk_name = os.path.join(final_dataset, "masks", f"case{i}_mask.jpg")
    shutil.copy(img, new_img_name)
    shutil.copy(msk, new_msk_name)

import zipfile
zip1 = "/content/drive/MyDrive/new_projectS_dataset/ed_training.zip"
zip2 = "/content/drive/MyDrive/new_projectS_dataset/ed_training_gt.zip"

with zipfile.ZipFile(zip1, 'r') as z1:
    print("ed_training.zip files:", z1.namelist()[:10])

with zipfile.ZipFile(zip2, 'r') as z2:
    print("ed_training_gt.zip files:", z2.namelist()[:10])

import zipfile, os, shutil
base_dir = "/content/drive/MyDrive/new_projectS_dataset/final_dataset"
img_dir = os.path.join(base_dir, "images")
msk_dir = os.path.join(base_dir, "masks")
os.makedirs(img_dir, exist_ok=True)
os.makedirs(msk_dir, exist_ok=True)
with zipfile.ZipFile("/content/drive/MyDrive/new_projectS_dataset/ed_training.zip", 'r') as zip_ref:
    zip_ref.extractall(base_dir)
with zipfile.ZipFile("/content/drive/MyDrive/new_projectS_dataset/ed_training_gt.zip", 'r') as zip_ref:
    zip_ref.extractall(base_dir)

import glob
imgs  = sorted(glob.glob(base_dir + "/ed_training/*.jpg"))
masks = sorted(glob.glob(base_dir + "/ed_training_gt/*.jpg"))
print("Total images:", len(imgs))
print("Total masks :", len(masks))
for i in range(100):
    shutil.copy(imgs[i], img_dir)
    shutil.copy(masks[i], msk_dir)

import matplotlib.pyplot as plt
from PIL import Image
images = sorted(os.listdir(img_dir))
masks  = sorted(os.listdir(msk_dir))
plt.figure(figsize=(10, 20))
for i in range(5):
    img = Image.open(os.path.join(img_dir, images[i]))
    msk = Image.open(os.path.join(msk_dir, masks[i]))
    plt.subplot(5, 2, 2*i+1)
    plt.imshow(img)
    plt.title(f"Case {i+1} - Image")
    plt.axis("off")

    plt.subplot(5, 2, 2*i+2)
    plt.imshow(msk, cmap="gray")
    plt.title(f"Case {i+1} - Mask")
    plt.axis("off")

plt.show()

import os
import shutil
img_dir = "/content/drive/MyDrive/new_projectS_dataset/final_dataset/images"
msk_dir = "/content/drive/MyDrive/new_projectS_dataset/final_dataset/masks"
new_img_dir = "/content/drive/MyDrive/new_projectS_dataset/final_dataset/renamed_images"
new_msk_dir = "/content/drive/MyDrive/new_projectS_dataset/final_dataset/renamed_masks"
os.makedirs(new_img_dir, exist_ok=True)
os.makedirs(new_msk_dir, exist_ok=True)
images = sorted(os.listdir(img_dir))
masks  = sorted(os.listdir(msk_dir))
print(f"Found {len(images)} images and {len(masks)} masks")
for i, (img, msk) in enumerate(zip(images, masks), start=1):
    new_img = f"case{i:03d}.jpg"
    new_msk = f"case{i:03d}_mask.jpg"

    shutil.copy(os.path.join(img_dir, img), os.path.join(new_img_dir, new_img))
    shutil.copy(os.path.join(msk_dir, msk), os.path.join(new_msk_dir, new_msk))

print("✅ Renaming done! Files saved in:")
print(new_img_dir)
print(new_msk_dir)

import os
import matplotlib.pyplot as plt
from PIL import Image
new_img_dir = "/content/drive/MyDrive/new_projectS_dataset/final_dataset/renamed_images"
new_msk_dir = "/content/drive/MyDrive/new_projectS_dataset/final_dataset/renamed_masks"
images = sorted(os.listdir(new_img_dir))
masks  = sorted(os.listdir(new_msk_dir))
for i in range(5):
    img_path = os.path.join(new_img_dir, images[i])
    msk_path = os.path.join(new_msk_dir, masks[i])

    img = Image.open(img_path)
    msk = Image.open(msk_path)

    plt.figure(figsize=(8,4))
    plt.subplot(1,2,1)
    plt.imshow(img)
    plt.title(f"Image: {images[i]}")
    plt.axis("off")
    plt.subplot(1,2,2)
    plt.imshow(msk, cmap="gray")
    plt.title(f"Mask: {masks[i]}")
    plt.axis("off")
    plt.show()

import os, json
import numpy as np
import cv2
from skimage.morphology import remove_small_objects, closing, disk
from skimage.measure import find_contours
from scipy.ndimage import distance_transform_edt as EDT

BASE = "/content/drive/MyDrive/new_projectS_dataset/final_dataset"
IMG_DIR = os.path.join(BASE, "renamed_images")
MSK_DIR = os.path.join(BASE, "renamed_masks")
SAVE_ROOT = os.path.join(BASE, "preproc")

RESIZE_TO = (128, 128)
N_INTERIOR = 5000
N_BOUNDARY = 1500
REMOVE_SMALL_AREA = 30
INLET_SIDE = "left"
INLET_BAND_FRAC = 0.05

os.makedirs(SAVE_ROOT, exist_ok=True)
images = sorted([f for f in os.listdir(IMG_DIR) if f.lower().endswith((".jpg",".png",".jpeg"))])
masks  = sorted([f for f in os.listdir(MSK_DIR) if f.lower().endswith((".jpg",".png",".jpeg"))])

print(f"Found {len(images)} renamed images and {len(masks)} renamed masks in:")
print("  ", IMG_DIR)
print("  ", MSK_DIR)

def imread_gray(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(path)
    return img

def imread_color(path):
    img = cv2.imread(path, cv2.IMREAD_COLOR)
    if img is None:
        raise FileNotFoundError(path)
    return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

def clean_mask(mask, remove_area=30, kernel_radius=2):
    mask01 = (mask > 127).astype(np.uint8)
    mask01 = remove_small_objects(mask01.astype(bool), remove_area).astype(np.uint8)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (2*kernel_radius+1, 2*kernel_radius+1))
    mask01 = cv2.morphologyEx(mask01, cv2.MORPH_CLOSE, kernel)
    return mask01

def compute_sdf(mask01):
    dist_inside  = EDT(mask01)
    dist_outside = EDT(1-mask01)
    sdf = dist_inside - dist_outside
    return sdf

def sample_boundary_points(mask01, n_points):
    contours = find_contours(mask01, 0.5)
    if len(contours) == 0:
        return np.zeros((0,2), dtype=np.int32)
    all_pts = np.vstack(contours)
    idx = np.random.choice(len(all_pts), min(n_points, len(all_pts)), replace=False)
    return all_pts[idx][:, ::-1]  # (x,y)

def sample_interior_points(mask01, n_points):
    ys, xs = np.where(mask01 > 0)
    coords = np.column_stack([xs, ys])
    if len(coords) == 0:
        return np.zeros((0,2), dtype=np.int32)
    idx = np.random.choice(len(coords), min(n_points, len(coords)), replace=False)
    return coords[idx]

def normalize_to_m1p1(coords, W, H):
    x = coords[:,0] / (W-1) * 2 - 1
    y = coords[:,1] / (H-1) * 2 - 1
    return np.column_stack([x,y]).astype(np.float32)

def make_eval_grid(W, H):
    Xg, Yg = np.meshgrid(np.arange(W), np.arange(H))
    return Xg, Yg

def infer_inlet_mask(mask01, side="left", band_frac=0.05):
    H, W = mask01.shape
    band_w = int(W*band_frac)
    if side == "left":
        band = np.zeros_like(mask01)
        band[:, :band_w] = 1
    elif side == "right":
        band = np.zeros_like(mask01)
        band[:, -band_w:] = 1
    else:
        raise ValueError("side must be 'left' or 'right'")
    return (mask01 & band).astype(np.uint8)

def save_preview(out_dir, img, mask, sdf, pts_int_px, pts_bnd_px, inlet_mask):
    import matplotlib.pyplot as plt
    fig, axs = plt.subplots(1,4, figsize=(12,3))
    axs[0].imshow(img); axs[0].set_title("Image")
    axs[1].imshow(mask, cmap="gray"); axs[1].set_title("Mask")
    axs[2].imshow(sdf, cmap="jet"); axs[2].set_title("SDF")
    axs[3].imshow(mask, cmap="gray")
    if len(pts_int_px) > 0:
        axs[3].scatter(pts_int_px[:,0], pts_int_px[:,1], s=2, c="blue")
    if len(pts_bnd_px) > 0:
        axs[3].scatter(pts_bnd_px[:,0], pts_bnd_px[:,1], s=2, c="red")
    axs[3].imshow(np.ma.masked_where(inlet_mask==0, inlet_mask), cmap="spring", alpha=0.5)
    axs[3].set_title("Samples + Inlet")
    for a in axs: a.axis("off")
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir,"preview.png"))
    plt.close()

num_cases = min(len(images), len(masks))
print("Processing", num_cases, "cases")

for idx in range(num_cases):
    img_path = os.path.join(IMG_DIR, images[idx])
    msk_path = os.path.join(MSK_DIR, masks[idx])

    case_id = f"case_{idx+1:04d}"
    out_dir = os.path.join(SAVE_ROOT, case_id)
    os.makedirs(out_dir, exist_ok=True)

    img_rgb = imread_color(img_path)
    mask_g  = imread_gray(msk_path)

    img_res = cv2.resize(img_rgb, RESIZE_TO, interpolation=cv2.INTER_CUBIC)
    msk_res = cv2.resize(mask_g,   RESIZE_TO, interpolation=cv2.INTER_NEAREST)

    mask01 = clean_mask(msk_res, remove_area=REMOVE_SMALL_AREA, kernel_radius=2)

    H, W = mask01.shape

    sdf = compute_sdf(mask01)

    pts_bnd_px = sample_boundary_points(mask01, N_BOUNDARY)
    pts_int_px = sample_interior_points(mask01, N_INTERIOR)

    pts_bnd = normalize_to_m1p1(pts_bnd_px, W, H)
    pts_int = normalize_to_m1p1(pts_int_px, W, H)

    inlet_mask = infer_inlet_mask(mask01, side=INLET_SIDE, band_frac=INLET_BAND_FRAC)
    inlet_coords_px = np.column_stack(np.where(inlet_mask == 1))
    if len(inlet_coords_px) > 0:
        inlet_coords_px = inlet_coords_px[:, ::-1]  # (x,y)
        inlet_coords = normalize_to_m1p1(inlet_coords_px, W, H)
        inlet_centroid_px = inlet_coords_px.mean(axis=0).tolist()
    else:
        inlet_coords = np.zeros((0,2), dtype=np.float32)
        inlet_centroid_px = None

    Xg, Yg = make_eval_grid(W, H)
    XYg = normalize_to_m1p1(np.stack([Xg.flatten(), Yg.flatten()], axis=1), W, H)
    Xg_norm = XYg[:,0].reshape(H, W).astype(np.float32)
    Yg_norm = XYg[:,1].reshape(H, W).astype(np.float32)

    np.save(os.path.join(out_dir, "mask.npy"),      mask01.astype(np.uint8))
    np.save(os.path.join(out_dir, "sdf.npy"),       sdf.astype(np.float32))
    np.save(os.path.join(out_dir, "pts_interior.npy"), pts_int)
    np.save(os.path.join(out_dir, "pts_boundary.npy"),  pts_bnd)
    np.save(os.path.join(out_dir, "X_grid.npy"),    Xg_norm)
    np.save(os.path.join(out_dir, "Y_grid.npy"),    Yg_norm)
    np.save(os.path.join(out_dir, "inlet_mask.npy"), inlet_mask.astype(np.uint8))

    meta = {
        "case_id": case_id,
        "image_path": img_path,
        "mask_path": msk_path,
        "H": int(H), "W": int(W),
        "resize_to": list(RESIZE_TO),
        "n_interior": int(len(pts_int)),
        "n_boundary": int(len(pts_bnd)),
        "inlet_side": INLET_SIDE,
        "inlet_band_frac": INLET_BAND_FRAC,
        "inlet_centroid_px": inlet_centroid_px
    }
    with open(os.path.join(out_dir, "meta.json"), "w") as f:
        json.dump(meta, f, indent=2)

    save_preview(out_dir, img_res, mask01, sdf, pts_int_px, pts_bnd_px, inlet_mask)

print(" ", SAVE_ROOT)

import os, json
import numpy as np
import matplotlib.pyplot as plt

BASE = "/content/drive/MyDrive/new_projectS_dataset/final_dataset/preproc"
CASE_ID = "case_0001"
case_dir = os.path.join(BASE, CASE_ID)

mask   = np.load(os.path.join(case_dir, "mask.npy"))
sdf    = np.load(os.path.join(case_dir, "sdf.npy"))
pts_in = np.load(os.path.join(case_dir, "pts_interior.npy"))
pts_bd = np.load(os.path.join(case_dir, "pts_boundary.npy"))
inlet  = np.load(os.path.join(case_dir, "inlet_mask.npy"))

with open(os.path.join(case_dir, "meta.json")) as f:
    meta = json.load(f)

print("Loaded", CASE_ID)
print("Image size:", mask.shape)
print("Interior points:", pts_in.shape, "Boundary points:", pts_bd.shape)

fig, axs = plt.subplots(1, 4, figsize=(16,4))

axs[0].imshow(mask, cmap="gray")
axs[0].set_title("Mask")

axs[1].imshow(sdf, cmap="jet")
axs[1].set_title("Signed Distance Field (SDF)")

axs[2].imshow(mask, cmap="gray")
axs[2].scatter(pts_in[:,0], pts_in[:,1], s=2, c="blue", label="interior")
axs[2].scatter(pts_bd[:,0], pts_bd[:,1], s=2, c="red", label="boundary")
axs[2].legend()
axs[2].set_title("Sampled Points")

axs[3].imshow(inlet, cmap="Reds")
axs[3].set_title("Inlet Mask")

for ax in axs:
    ax.axis("off")

plt.tight_layout()
plt.show()

# Commented out IPython magic to ensure Python compatibility.
!pip install deepxde
!pip install torch torchvision torchaudio --upgrade
!pip install numpy pandas scikit-learn matplotlib seaborn
# %matplotlib inline
import torch, deepxde, numpy as np, pandas as pd, sklearn
print("Torch:", torch.__version__)
print("DeepXDE:", deepxde.__version__)
print("NumPy:", np.__version__)
print("pandas:", pd.__version__)

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

!pip install deepxde torch torchvision scikit-image opencv-python scikit-learn

import os
os.environ["DDE_BACKEND"] = "pytorch"
import torch
import deepxde as dde
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)
torch.set_default_dtype(torch.float32)
print("DeepXDE backend:", dde.backend.backend_name)
print("Using device:", device)

!pip install deepxde torch torchvision scikit-image opencv-python scikit-learn

from google.colab import drive
drive.mount('/content/drive')

import os, json
import numpy as np
import deepxde as dde
import torch
import cv2
from skimage import measure
from sklearn.model_selection import train_test_split
from tqdm import tqdm

torch.set_default_dtype(torch.float32)
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)
print("Using device:", device, flush=True)

CASE_DIR = "/content/drive/MyDrive/new_projectCdataset/final_dataset/preproc/Case_0100"
OUT_ROOT = os.path.join(CASE_DIR, "pinn_resultsNew")
os.makedirs(OUT_ROOT, exist_ok=True)

rho = 1.0
mu = 0.01

cases = sorted([d for d in os.listdir(CASE_DIR) if d.startswith("case")])
cases = cases[:70]

def normalize_to_m1p1(coords_xy, W, H):
    x = coords_xy[:, 0]
    y = coords_xy[:, 1]
    x_norm = 2.0 * (x / (W - 1.0)) - 1.0
    y_norm = 2.0 * (y / (H - 1.0)) - 1.0
    return np.stack([x_norm, y_norm], axis=1).astype(np.float32)

for idx, case_name in enumerate(tqdm(cases, desc="Training per-geometry PINNs", unit="case"), 1):
    print(f"\n➡️ Starting training for {case_name} ({idx}/{len(cases)})", flush=True)

    case_path = os.path.join(CASE_DIR, case_name)
    case_out_dir = os.path.join(OUT_ROOT, case_name)
    os.makedirs(case_out_dir, exist_ok=True)

    X_int = np.load(os.path.join(case_path, "pts_interior.npy"))
    Xg = np.load(os.path.join(case_path, "X_grid.npy"))
    Yg = np.load(os.path.join(case_path, "Y_grid.npy"))
    mask01 = np.load(os.path.join(case_path, "mask.npy")).astype(np.uint8)

    H, W = mask01.shape
    X_grid = np.stack([Xg.flatten(), Yg.flatten()], axis=1).astype(np.float32)

    X_train, X_test = train_test_split(X_int, test_size=0.4, random_state=42)

    def ns_residuals(x, y):
        u, v, p = y[:, 0:1], y[:, 1:2], y[:, 2:3]
        u_x = dde.grad.jacobian(y, x, i=0, j=0)
        u_y = dde.grad.jacobian(y, x, i=0, j=1)
        v_x = dde.grad.jacobian(y, x, i=1, j=0)
        v_y = dde.grad.jacobian(y, x, i=1, j=1)
        p_x = dde.grad.jacobian(y, x, i=2, j=0)
        p_y = dde.grad.jacobian(y, x, i=2, j=1)

        u_xx = dde.grad.hessian(y, x, i=0, j=0)
        u_yy = dde.grad.hessian(y, x, i=0, j=1)
        v_xx = dde.grad.hessian(y, x, i=1, j=0)
        v_yy = dde.grad.hessian(y, x, i=1, j=1)

        eq1 = u_x + v_y
        eq2 = rho * (u * u_x + v * u_y) + p_x - mu * (u_xx + u_yy)
        eq3 = rho * (u * v_x + v * v_y) + p_y - mu * (v_xx + v_yy)
        return [eq1, eq2, eq3]

    contours = measure.find_contours(mask01, 0.5)
    contour = max(contours, key=len)
    bnd_pts = np.fliplr(contour)
    bnd_pts_norm = normalize_to_m1p1(bnd_pts, W, H)

    geom = dde.geometry.PointCloud(X_train, boundary_points=bnd_pts_norm)

    def on_boundary_any(x, on_boundary):
        return on_boundary

    bc_u_wall = dde.DirichletBC(geom, lambda x: 0, on_boundary_any, component=0)
    bc_v_wall = dde.DirichletBC(geom, lambda x: 0, on_boundary_any, component=1)
    bcs = [bc_u_wall, bc_v_wall]

    net = dde.maps.FNN([2] + [64]*6 + [3], "tanh", "Glorot normal")
    data = dde.data.PDE(geom, ns_residuals, bcs, num_domain=5000, num_boundary=1500)
    model = dde.Model(data, net)

    print(f"Training {case_name} with Adam...", flush=True)
    model.compile("adam", lr=1e-3)
    model.train(epochs=3000, display_every=500)

    print(f"Training {case_name} with L-BFGS...", flush=True)
    model.compile("L-BFGS")
    model.train()

    Y_pred = model.predict(X_grid)
    u_pred = Y_pred[:, 0].reshape(H, W)
    v_pred = Y_pred[:, 1].reshape(H, W)
    p_pred = Y_pred[:, 2].reshape(H, W)

    np.save(os.path.join(case_out_dir, f"{case_name}_u.npy"), u_pred)
    np.save(os.path.join(case_out_dir, f"{case_name}_v.npy"), v_pred)
    np.save(os.path.join(case_out_dir, f"{case_name}_p.npy"), p_pred)

    def op_residuals(x, y):
        eq1, eq2, eq3 = ns_residuals(x, y)
        return torch.cat([eq1, eq2, eq3], dim=1)

    R = model.predict(X_grid, operator=op_residuals)
    r_cont = R[:, 0].reshape(H, W)
    r_momx = R[:, 1].reshape(H, W)
    r_momy = R[:, 2].reshape(H, W)

    np.save(os.path.join(case_out_dir, f"{case_name}_resdcont.npy"), r_cont)
    np.save(os.path.join(case_out_dir, f"{case_name}_resdm_x.npy"), r_momx)
    np.save(os.path.join(case_out_dir, f"{case_name}_resdm_y.npy"), r_momy)

    metrics = {
        "continuity_mean_abs": float(np.mean(np.abs(r_cont))),
        "continuity_L2": float(np.sqrt(np.mean(r_cont**2))),
        "momx_mean_abs": float(np.mean(np.abs(r_momx))),
        "momx_L2": float(np.sqrt(np.mean(r_momx**2))),
        "momy_mean_abs": float(np.mean(np.abs(r_momy))),
        "momy_L2": float(np.sqrt(np.mean(r_momy**2))),
    }
    with open(os.path.join(case_out_dir, f"{case_name}_resd_metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)

    def compute_boundary_normals(mask01):
        contours = measure.find_contours(mask01, 0.5)
        contour = max(contours, key=len)
        pts_px = np.fliplr(contour)
        dist_out = cv2.distanceTransform((1 - mask01).astype(np.uint8), cv2.DIST_L2, 5)
        gy, gx = np.gradient(dist_out.astype(np.float32))
        g = np.stack([gx, gy], axis=-1)
        norms = np.linalg.norm(g, axis=-1, keepdims=True) + 1e-8
        normals_field = g / norms
        xi = np.clip(pts_px[:, 0].astype(int), 0, mask01.shape[1]-1)
        yi = np.clip(pts_px[:, 1].astype(int), 0, mask01.shape[0]-1)
        normals_px = normals_field[yi, xi]
        return pts_px, normals_px

    bnd_pts_px, normals_px = compute_boundary_normals(mask01)
    bnd_pts_norm = normalize_to_m1p1(bnd_pts_px, W, H)

    def op_vel_jac(x, y):
        u_x = dde.grad.jacobian(y, x, i=0, j=0)
        u_y = dde.grad.jacobian(y, x, i=0, j=1)
        v_x = dde.grad.jacobian(y, x, i=1, j=0)
        v_y = dde.grad.jacobian(y, x, i=1, j=1)
        return torch.cat([u_x, u_y, v_x, v_y], dim=1)

    Jb = model.predict(bnd_pts_norm, operator=op_vel_jac)
    u_x, u_y, v_x, v_y = [Jb[:, i:i+1] for i in range(4)]
    J = np.stack([np.concatenate([u_x, u_y], axis=1),
                  np.concatenate([v_x, v_y], axis=1)], axis=1)

    normals = normals_px.astype(np.float32)
    norms = np.linalg.norm(normals, axis=1, keepdims=True) + 1e-8
    normals = normals / norms
    tangents = np.stack([-normals[:, 1], normals[:, 0]], axis=1)

    Jn = np.einsum("bij,bj->bi", J, normals)
    t_dot_Jn = np.sum(tangents * Jn, axis=1, keepdims=True)
    wss = mu * t_dot_Jn

    np.save(os.path.join(case_out_dir, f"{case_name}_wss.npy"), wss)
    print(f"Completed {case_name} ({idx}/{len(cases)})", flush=True)

!nvidia-smi

import os, json
import numpy as np
import deepxde as dde
import torch
import cv2
from skimage import measure
from sklearn.model_selection import train_test_split
torch.set_default_dtype(torch.float32)
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)
print("Using device:", device)
CASE_DIR = "/content/drive/MyDrive/new_projectS_dataset/final_dataset/preproc"
OUT_ROOT = os.path.join(CASE_DIR, "pinn_resultsNew")
os.makedirs(OUT_ROOT, exist_ok=True)

rho = 1.0
mu = 0.01

cases = sorted([
    d for d in os.listdir(CASE_DIR)
    if d.startswith("case") and os.path.isdir(os.path.join(CASE_DIR, d))
])
cases = cases[:70]
print(f"Found {len(cases)} cases for training.")
def normalize_to_m1p1(coords_xy, W, H):
    x = coords_xy[:, 0]
    y = coords_xy[:, 1]
    x_norm = 2.0 * (x / (W - 1.0)) - 1.0
    y_norm = 2.0 * (y / (H - 1.0)) - 1.0
    return np.stack([x_norm, y_norm], axis=1).astype(np.float32)
for idx, case_name in enumerate(cases, 1):
    print(f"\n Starting training for {case_name} ({idx}/{len(cases)})")
    case_path = os.path.join(CASE_DIR, case_name)
    case_out_dir = os.path.join(OUT_ROOT, case_name)
    os.makedirs(case_out_dir, exist_ok=True)
    X_int = np.load(os.path.join(case_path, "pts_interior.npy"))
    Xg = np.load(os.path.join(case_path, "X_grid.npy"))
    Yg = np.load(os.path.join(case_path, "Y_grid.npy"))
    mask01 = np.load(os.path.join(case_path, "mask.npy")).astype(np.uint8)
    H, W = mask01.shape
    X_grid = np.stack([Xg.flatten(), Yg.flatten()], axis=1).astype(np.float32)
    X_train, X_test = train_test_split(X_int, test_size=0.4, random_state=42)
    def ns_residuals(x, y):
        u, v, p = y[:, 0:1], y[:, 1:2], y[:, 2:3]
        u_x = dde.grad.jacobian(y, x, i=0, j=0)
        u_y = dde.grad.jacobian(y, x, i=0, j=1)
        v_x = dde.grad.jacobian(y, x, i=1, j=0)
        v_y = dde.grad.jacobian(y, x, i=1, j=1)
        p_x = dde.grad.jacobian(y, x, i=2, j=0)
        p_y = dde.grad.jacobian(y, x, i=2, j=1)

        u_xx = dde.grad.hessian(y, x, i=0, j=0)
        u_yy = dde.grad.hessian(y, x, i=0, j=1)
        v_xx = dde.grad.hessian(y, x, i=1, j=0)
        v_yy = dde.grad.hessian(y, x, i=1, j=1)

        eq1 = u_x + v_y
        eq2 = rho * (u * u_x + v * u_y) + p_x - mu * (u_xx + u_yy)
        eq3 = rho * (u * v_x + v * v_y) + p_y - mu * (v_xx + v_yy)
        return [eq1, eq2, eq3]
    contours = measure.find_contours(mask01, 0.5)
    contour = max(contours, key=len)
    bnd_pts = np.fliplr(contour)
    bnd_pts_norm = normalize_to_m1p1(bnd_pts, W, H)
    geom = dde.geometry.PointCloud(X_train, boundary_points=bnd_pts_norm)
    def on_boundary_any(x, on_boundary):
        return on_boundary
    bc_u_wall = dde.DirichletBC(geom, lambda x: 0, on_boundary_any, component=0)
    bc_v_wall = dde.DirichletBC(geom, lambda x: 0, on_boundary_any, component=1)
    bcs = [bc_u_wall, bc_v_wall]
    net = dde.maps.FNN([2] + [64]*6 + [3], "tanh", "Glorot normal")
    data = dde.data.PDE(geom, ns_residuals, bcs, num_domain=5000, num_boundary=1500)
    model = dde.Model(data, net)
    print(f"Training PINN for {case_name} ...")
    model.compile("adam", lr=1e-3)
    model.train(epochs=2000, display_every=500)
    model.compile("L-BFGS")
    model.train()
    print(f"Finished training {case_name}")
    Y_pred = model.predict(X_grid)
    u_pred = Y_pred[:, 0].reshape(H, W)
    v_pred = Y_pred[:, 1].reshape(H, W)
    p_pred = Y_pred[:, 2].reshape(H, W)
    np.save(os.path.join(case_out_dir, f"{case_name}_u.npy"), u_pred)
    np.save(os.path.join(case_out_dir, f"{case_name}_v.npy"), v_pred)
    np.save(os.path.join(case_out_dir, f"{case_name}_p.npy"), p_pred)
    def op_residuals(x, y):
        eq1, eq2, eq3 = ns_residuals(x, y)
        return torch.cat([eq1, eq2, eq3], dim=1)
    R = model.predict(X_grid, operator=op_residuals)
    r_cont = R[:, 0].reshape(H, W)
    r_momx = R[:, 1].reshape(H, W)
    r_momy = R[:, 2].reshape(H, W)
    np.save(os.path.join(case_out_dir, f"{case_name}_resdcont.npy"), r_cont)
    np.save(os.path.join(case_out_dir, f"{case_name}_resdm_x.npy"), r_momx)
    np.save(os.path.join(case_out_dir, f"{case_name}_resdm_y.npy"), r_momy)
    metrics = {
        "continuity_mean_abs": float(np.mean(np.abs(r_cont))),
        "continuity_L2": float(np.sqrt(np.mean(r_cont**2))),
        "momx_mean_abs": float(np.mean(np.abs(r_momx))),
        "momx_L2": float(np.sqrt(np.mean(r_momx**2))),
        "momy_mean_abs": float(np.mean(np.abs(r_momy))),
        "momy_L2": float(np.sqrt(np.mean(r_momy**2))),
    }
    with open(os.path.join(case_out_dir, f"{case_name}_resd_metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)
    def compute_boundary_normals(mask01):
        contours = measure.find_contours(mask01, 0.5)
        contour = max(contours, key=len)
        pts_px = np.fliplr(contour)
        dist_out = cv2.distanceTransform((1 - mask01).astype(np.uint8), cv2.DIST_L2, 5)
        gy, gx = np.gradient(dist_out.astype(np.float32))
        g = np.stack([gx, gy], axis=-1)
        norms = np.linalg.norm(g, axis=-1, keepdims=True) + 1e-8
        normals_field = g / norms
        xi = np.clip(pts_px[:, 0].astype(int), 0, mask01.shape[1]-1)
        yi = np.clip(pts_px[:, 1].astype(int), 0, mask01.shape[0]-1)
        normals_px = normals_field[yi, xi]
        return pts_px, normals_px
    bnd_pts_px, normals_px = compute_boundary_normals(mask01)
    bnd_pts_norm = normalize_to_m1p1(bnd_pts_px, W, H)
    def op_vel_jac(x, y):
        u_x = dde.grad.jacobian(y, x, i=0, j=0)
        u_y = dde.grad.jacobian(y, x, i=0, j=1)
        v_x = dde.grad.jacobian(y, x, i=1, j=0)
        v_y = dde.grad.jacobian(y, x, i=1, j=1)
        return torch.cat([u_x, u_y, v_x, v_y], dim=1)
    Jb = model.predict(bnd_pts_norm, operator=op_vel_jac)
    u_x, u_y, v_x, v_y = [Jb[:, i:i+1] for i in range(4)]
    J = np.stack([np.concatenate([u_x, u_y], axis=1),
                  np.concatenate([v_x, v_y], axis=1)], axis=1)
    normals = normals_px.astype(np.float32)
    norms = np.linalg.norm(normals, axis=1, keepdims=True) + 1e-8
    normals = normals / norms
    tangents = np.stack([-normals[:, 1], normals[:, 0]], axis=1)
    Jn = np.einsum("bij,bj->bi", J, normals)
    t_dot_Jn = np.sum(tangents * Jn, axis=1, keepdims=True)
    wss = mu * t_dot_Jn
    np.save(os.path.join(case_out_dir, f"{case_name}_wss.npy"), wss)

import os
import numpy as np
import cv2
import json
import pandas as pd
from tqdm import tqdm
PINN_DIR = "/content/drive/MyDrive/new_projectS_dataset/final_dataset/preproc/pinn_resultsNew"
PREPROC_DIR = "/content/drive/MyDrive/new_projectS_dataset/final_dataset/preproc"
OUT_DATASET_DIR = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf"
os.makedirs(OUT_DATASET_DIR, exist_ok=True)
TARGET_RES = (64, 64)
DEFAULT_BC = {
    "inlet": {"u": 1.0, "v": 0.0},
    "outlet": {"p": 0.0},
    "walls": {"u": 0.0, "v": 0.0}
}
cases = sorted([d for d in os.listdir(PINN_DIR) if d.startswith("case")])
all_u, all_v, all_p = [], [], []
for case_name in tqdm(cases, desc="Collecting fields for normalization"):
    case_pinn_path = os.path.join(PINN_DIR, case_name)
    u = np.load(os.path.join(case_pinn_path, f"{case_name}_u.npy"))
    v = np.load(os.path.join(case_pinn_path, f"{case_name}_v.npy"))
    p = np.load(os.path.join(case_pinn_path, f"{case_name}_p.npy"))
    all_u.append(u)
    all_v.append(v)
    all_p.append(p)
velocity_scale = max(np.max(np.abs(np.concatenate(all_u))), np.max(np.abs(np.concatenate(all_v))))
pressure_scale = np.max(np.abs(np.concatenate(all_p)))
print(f"Velocity scale: {velocity_scale:.6f}, Pressure scale: {pressure_scale:.6f}")
with open(os.path.join(OUT_DATASET_DIR, "scalers.json"), "w") as f:
    json.dump({"velocity_scale": float(velocity_scale),
               "pressure_scale": float(pressure_scale)}, f, indent=2)
index_list = []
for case_name in tqdm(cases, desc="Creating normalized dataset"):
    case_pinn_path = os.path.join(PINN_DIR, case_name)
    case_preproc_path = os.path.join(PREPROC_DIR, case_name)

    mask = np.load(os.path.join(case_preproc_path, "mask.npy"))
    u = np.load(os.path.join(case_pinn_path, f"{case_name}_u.npy"))
    v = np.load(os.path.join(case_pinn_path, f"{case_name}_v.npy"))
    p = np.load(os.path.join(case_pinn_path, f"{case_name}_p.npy"))

    u /= velocity_scale
    v /= velocity_scale
    p /= pressure_scale

    mask_64 = cv2.resize(mask.astype(np.float32), TARGET_RES, interpolation=cv2.INTER_NEAREST)
    u_64 = cv2.resize(u.astype(np.float32), TARGET_RES, interpolation=cv2.INTER_LINEAR)
    v_64 = cv2.resize(v.astype(np.float32), TARGET_RES, interpolation=cv2.INTER_LINEAR)
    p_64 = cv2.resize(p.astype(np.float32), TARGET_RES, interpolation=cv2.INTER_LINEAR)

    case_out_dir = os.path.join(OUT_DATASET_DIR, case_name)
    os.makedirs(case_out_dir, exist_ok=True)
    np.save(os.path.join(case_out_dir, "mask_64.npy"), mask_64)
    np.save(os.path.join(case_out_dir, "u_64.npy"), u_64)
    np.save(os.path.join(case_out_dir, "v_64.npy"), v_64)
    np.save(os.path.join(case_out_dir, "p_64.npy"), p_64)
    bc_path = os.path.join(case_out_dir, "bc.json")
    with open(bc_path, "w") as f:
        json.dump(DEFAULT_BC, f, indent=2)
    index_list.append({
        "case": case_name,
        "mask": os.path.join(case_out_dir, "mask_64.npy"),
        "u": os.path.join(case_out_dir, "u_64.npy"),
        "v": os.path.join(case_out_dir, "v_64.npy"),
        "p": os.path.join(case_out_dir, "p_64.npy"),
        "bc": bc_path
    })
index_df = pd.DataFrame(index_list)
index_csv_path = os.path.join(OUT_DATASET_DIR, "index.csv")
index_df.to_csv(index_csv_path, index=False)
print(f"{OUT_DATASET_DIR}, {index_csv_path}")

from google.colab import drive
drive.mount('/content/drive')

import os, json, numpy as np, torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)
DATASET_DIR = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf"
CASE_LIST = sorted([d for d in os.listdir(DATASET_DIR) if d.startswith("case")])
print(f"Found {len(CASE_LIST)} cases")
class DeepONetDataset(Dataset):
    def __init__(self, cases, dataset_dir):
        self.branch_list = []
        self.trunk_list = []
        self.fields_list = []

        for case_name in cases:
            case_dir = os.path.join(dataset_dir, case_name)
            mask = np.load(os.path.join(case_dir, "mask_64.npy")).astype(np.float32)[None, :, :]
            u = np.load(os.path.join(case_dir, "u_64.npy")).astype(np.float32)
            v = np.load(os.path.join(case_dir, "v_64.npy")).astype(np.float32)
            p = np.load(os.path.join(case_dir, "p_64.npy")).astype(np.float32)

            H, W = u.shape
            x = np.linspace(0, 1, W)
            y = np.linspace(0, 1, H)
            xv, yv = np.meshgrid(x, y)
            coords = np.stack([xv, yv], axis=-1).astype(np.float32)

            self.branch_list.append(torch.tensor(mask))
            self.trunk_list.append(torch.tensor(coords))
            self.fields_list.append(torch.tensor(np.stack([u, v, p], axis=-1)))
    def __len__(self):
        return len(self.branch_list)
    def __getitem__(self, idx):
        return self.branch_list[idx], self.trunk_list[idx], self.fields_list[idx]
class DeepONet(nn.Module):
    def __init__(self, branch_channels=1, trunk_dim=2, latent_dim=128, out_dim=3):
        super().__init__()
        self.branch_net = nn.Sequential(
            nn.Conv2d(branch_channels, 16, 3, padding=1), nn.ReLU(),
            nn.Conv2d(16, 32, 3, padding=1), nn.ReLU(),
            nn.Conv2d(32, latent_dim, 3, padding=1), nn.ReLU(),
            nn.AdaptiveAvgPool2d(1)
        )
        self.trunk_net = nn.Sequential(
            nn.Linear(trunk_dim, 64), nn.ReLU(),
            nn.Linear(64, latent_dim)
        )
        self.fc_out = nn.Linear(latent_dim, out_dim)
    def forward(self, branch, coords):
        B, _, H, W = branch.shape
        branch_latent = self.branch_net(branch).view(B, -1)
        trunk_latent = self.trunk_net(coords.view(B, -1, 2))
        branch_latent_exp = branch_latent[:, None, :]
        fused = branch_latent_exp * trunk_latent
        out = self.fc_out(fused)
        return out.view(B, H, W, 3)
EPOCHS = 100
BATCH_SIZE = 1
LEARNING_RATE = 1e-4
dataset = DeepONetDataset(CASE_LIST, DATASET_DIR)
dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)
model = DeepONet().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
criterion = nn.MSELoss()
for epoch in range(1, EPOCHS+1):
    model.train()
    epoch_loss = 0
    for mask, coords, fields in tqdm(dataloader, desc=f"Epoch {epoch}"):
        mask = mask.float().to(device)
        coords = coords.float().to(device)
        fields = fields.float().to(device)
        optimizer.zero_grad()
        pred = model(mask, coords)
        loss = criterion(pred, fields)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
    print(f"Epoch {epoch}/{EPOCHS} - Loss: {epoch_loss/len(dataloader):.6f}")
torch.save(model.state_dict(), os.path.join(DATASET_DIR, "dON_check.pt"))



import os
import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
DATASET_DIR = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf"
OUT_FEATURES_CSV = os.path.join(DATASET_DIR, "features.csv")
OUT_LABELS_CSV = os.path.join(DATASET_DIR, "labels_disease.csv")
cases = sorted([d for d in os.listdir(DATASET_DIR) if d.startswith("case")])
features_list = []
for case_name in tqdm(cases, desc="Extracting features"):
    case_dir = os.path.join(DATASET_DIR, case_name)
    try:
        mask = np.load(os.path.join(case_dir, "mask_64.npy"))
        u = np.load(os.path.join(case_dir, "u_64.npy"))
        v = np.load(os.path.join(case_dir, "v_64.npy"))
        p = np.load(os.path.join(case_dir, "p_64.npy"))
        wss_path = os.path.join(case_dir.replace("sixf", "preproc/pinn_resultsNew"), f"{case_name}_wss.npy")
        if os.path.exists(wss_path):
            wss = np.load(wss_path)
        else:
            wss = np.zeros_like(u)
        if mask is None or u is None or v is None or p is None:
            print(f"Skipping {case_name}: missing data")
            continue
        mask_area = np.sum(mask > 0) / mask.size
        u_mean, u_max, u_std = np.mean(u), np.max(u), np.std(u)
        v_mean, v_max, v_std = np.mean(v), np.max(v), np.std(v)
        p_mean, p_max, p_min, p_std = np.mean(p), np.max(p), np.min(p), np.std(p)
        pressure_drop = p_max - p_min
        dudx = np.gradient(u, axis=1)
        dvdy = np.gradient(v, axis=0)
        du_dy = np.gradient(u, axis=0)
        dv_dx = np.gradient(v, axis=1)
        vorticity = dv_dx - du_dy
        recirc_frac = np.sum(vorticity < 0) / vorticity.size
        wss_mean = np.mean(wss)
        wss_max = np.max(wss)
        wss_std = np.std(wss)
        features_list.append({
            "case": case_name,
            "mask_area": mask_area,
            "u_mean": u_mean,
            "u_max": u_max,
            "u_std": u_std,
            "v_mean": v_mean,
            "v_max": v_max,
            "v_std": v_std,
            "p_mean": p_mean,
            "p_max": p_max,
            "p_min": p_min,
            "p_std": p_std,
            "pressure_drop": pressure_drop,
            "recirc_frac": recirc_frac,
            "wss_mean": wss_mean,
            "wss_max": wss_max,
            "wss_std": wss_std
        })

    except Exception as e:
        print(f"Skipping {case_name} due to error: {e}")
        continue
df_features = pd.DataFrame(features_list)
print("Extracted features shape:", df_features.shape)
df_features.to_csv(OUT_FEATURES_CSV, index=False)
print("Features saved to:", OUT_FEATURES_CSV)
X = df_features.drop(columns=["case"]).values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
kmeans = KMeans(n_clusters=5, random_state=42)
df_features["pseudo_label"] = kmeans.fit_predict(X_scaled)
pseudo_to_disease = {
    0: "normal",
    1: "aneurysm",
    2: "stenosis",
    3: "atherosclerosis",
    4: "valve_defect"
}
df_features["disease"] = df_features["pseudo_label"].map(pseudo_to_disease)
df_features[["case", "pseudo_label", "disease"]].to_csv(OUT_LABELS_CSV, index=False)

import os
import numpy as np
import pandas as pd
from tqdm import tqdm
DATASET_DIR = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf"
cases = sorted([d for d in os.listdir(DATASET_DIR) if d.startswith("case")])
feature_list = []
for case_name in tqdm(cases, desc="Extracting features"):
    case_dir = os.path.join(DATASET_DIR, case_name)
    u = np.load(os.path.join(case_dir, "u_64.npy"))
    v = np.load(os.path.join(case_dir, "v_64.npy"))
    p = np.load(os.path.join(case_dir, "p_64.npy"))
    mask = np.load(os.path.join(case_dir, "mask_64.npy"))
    vel_mag = np.sqrt(u**2 + v**2)
    u_mean, u_max, u_std = np.mean(u), np.max(u), np.std(u)
    v_mean, v_max, v_std = np.mean(v), np.max(v), np.std(v)
    vel_mean, vel_max, vel_std = np.mean(vel_mag), np.max(vel_mag), np.std(vel_mag)
    p_mean, p_max, p_min, p_std = np.mean(p), np.max(p), np.min(p), np.std(p)
    upstream_idx, downstream_idx = 0, -1
    pressure_drop = np.mean(p[upstream_idx, :]) - np.mean(p[downstream_idx, :])
    dv_dx = np.gradient(v, axis=1)
    du_dy = np.gradient(u, axis=0)
    vorticity = dv_dx - du_dy
    vort_mean, vort_max, vort_std = np.mean(vorticity), np.max(vorticity), np.std(vorticity)
    recirc_frac = np.sum(u < 0) / (u.shape[0]*u.shape[1])
    from skimage import measure
    contours = measure.find_contours(mask, 0.5)
    if len(contours) > 0:
        boundary = max(contours, key=len)
        boundary = np.fliplr(boundary).astype(int)
        wss_vals = []
        for x, y in boundary:
            x1, x2 = max(x-1,0), min(x+1,u.shape[1]-1)
            y1, y2 = max(y-1,0), min(y+1,u.shape[0]-1)
            du_dx = (u[y,x2] - u[y,x1])/2.0
            dv_dy = (v[y2,x] - v[y1,x])/2.0
            tau = np.sqrt(du_dx**2 + dv_dy**2)
            wss_vals.append(tau)
        wss_vals = np.array(wss_vals)
        wss_mean, wss_max, wss_std = np.mean(wss_vals), np.max(wss_vals), np.std(wss_vals)
    else:
        wss_mean = wss_max = wss_std = 0.0
    area = np.sum(mask)
    widths = np.sum(mask, axis=0)
    min_width = np.min(widths) if len(widths)>0 else 0
    eccentricity = np.std(np.argwhere(mask>0), axis=0).max() if np.sum(mask)>0 else 0
    features = {
        "case": case_name,
        "u_mean": u_mean, "u_max": u_max, "u_std": u_std,
        "v_mean": v_mean, "v_max": v_max, "v_std": v_std,
        "vel_mean": vel_mean, "vel_max": vel_max, "vel_std": vel_std,
        "p_mean": p_mean, "p_max": p_max, "p_min": p_min, "p_std": p_std,
        "pressure_drop": pressure_drop,
        "vort_mean": vort_mean, "vort_max": vort_max, "vort_std": vort_std,
        "recirc_frac": recirc_frac,
        "wss_mean": wss_mean, "wss_max": wss_max, "wss_std": wss_std,
        "area": area, "min_width": min_width, "eccentricity": eccentricity
    }
    feature_list.append(features)
df_features_new = pd.DataFrame(feature_list)
features_path = os.path.join(DATASET_DIR, "features_enhanced.csv")
df_features_new.to_csv(features_path, index=False)

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib
FEATURES_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/features_enhanced.csv"
LABELS_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/labels_disease.csv"
MODEL_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/xgb_classifier.pkl"
SCALER_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/feature_scaler.pkl"
df_features = pd.read_csv(FEATURES_PATH)
df_labels = pd.read_csv(LABELS_PATH)
df = df_features.merge(df_labels[['case', 'disease']], on='case')
print("Merged data shape:", df.shape)
X = df.drop(columns=['case', 'disease']).values
y = df['disease'].values
le = LabelEncoder()
y_encoded = le.fit_transform(y)
print("Classes:", le.classes_)
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)
print("After SMOTE, training set shape:", X_train_res.shape)
clf = XGBClassifier(
    objective='multi:softprob',
    num_class=len(le.classes_),
    eval_metric='mlogloss',
    use_label_encoder=False,
    n_estimators=200,
    max_depth=3,
    learning_rate=0.1,
    random_state=42
)
clf.fit(X_train_res, y_train_res)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("\nTest Accuracy: {:.4f}".format(acc))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
joblib.dump(clf, MODEL_PATH)
joblib.dump(scaler, SCALER_PATH)
joblib.dump(le, "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/label_encoder.pkl")

print("\nSaved model to:", MODEL_PATH)
print("Saved scaler to:", SCALER_PATH)

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np
import xgboost as xgb
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler, LabelEncoder
import joblib
import pandas as pd

FEATURES_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/features_enhanced_v2.csv"
LABELS_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/labels_disease.csv"
MODEL_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/xgb_ensemble_model.pkl"
SCALER_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/feature_scaler_v2.pkl"
ENCODER_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/label_encoder_v2.pkl"

df_features = pd.read_csv(FEATURES_PATH)
df_labels = pd.read_csv(LABELS_PATH)
df = df_features.merge(df_labels[['case','disease']], on='case')
X = df.drop(columns=["case","disease"]).values
y = df["disease"].values
le = LabelEncoder()
y_encoded = le.fit_transform(y)
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
fold_accuracies = []

for fold, (train_idx, test_idx) in enumerate(kf.split(X, y_encoded), 1):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]
    smote = SMOTE(random_state=42)
    X_train_res, y_train_res = smote.fit_resample(X_train, y_train)
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train_res)
    X_test_scaled = scaler.transform(X_test)
    clf = xgb.XGBClassifier(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        objective='multi:softmax',
        num_class=len(le.classes_),
        random_state=42,
        use_label_encoder=False,
        eval_metric='mlogloss'
    )
    clf.fit(X_train_scaled, y_train_res)
    y_pred = clf.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    fold_accuracies.append(acc)
print(f"Fold 5 Accuracy: {fold_accuracies[4]:.4f}")



import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
import xgboost as xgb
import joblib

FEATURES_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/features_enhanced_v2.csv"
LABELS_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/labels_disease.csv"
MODEL_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/ensemble_model_v3.pkl"
SCALER_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/feature_scaler_v3.pkl"
ENCODER_PATH = "/content/drive/MyDrive/new_projectS_dataset/dataset/sixf/label_encoder_v3.pkl"

df_features = pd.read_csv(FEATURES_PATH)
df_labels = pd.read_csv(LABELS_PATH)
df = df_features.merge(df_labels[['case','disease']], on='case')

X = df.drop(columns=["case","disease"]).values
y = df["disease"].values

le = LabelEncoder()
y_encoded = le.fit_transform(y)
print("Classes:", le.classes_)

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
fold_accuracies = []

for fold, (train_idx, test_idx) in enumerate(kf.split(X, y_encoded), 1):


    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    smote = SMOTE(random_state=42)
    X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train_res)
    X_test_scaled = scaler.transform(X_test)

    clf_xgb = xgb.XGBClassifier(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        objective='multi:softprob',
        num_class=len(le.classes_),
        random_state=42,
        eval_metric='mlogloss'
    )

    clf_rf = RandomForestClassifier(
        n_estimators=500,
        max_depth=8,
        random_state=42
    )

    clf_gb = GradientBoostingClassifier(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=5,
        random_state=42
    )

    ensemble = VotingClassifier(
        estimators=[('xgb', clf_xgb), ('rf', clf_rf), ('gb', clf_gb)],
        voting='soft'
    )

    ensemble.fit(X_train_scaled, y_train_res)
    y_pred = ensemble.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    fold_accuracies.append(acc)
y_pred_full = ensemble.predict(scaler.transform(X))
print("\nOverall Accuracy:", accuracy_score(y_encoded, y_pred_full))
print("\nClassification Report:")
print(classification_report(y_encoded, y_pred_full, target_names=le.classes_))
print("\nConfusion Matrix:")
print(confusion_matrix(y_encoded, y_pred_full))
joblib.dump(ensemble, MODEL_PATH)
joblib.dump(scaler, SCALER_PATH)
joblib.dump(le, ENCODER_PATH)

import matplotlib.pyplot as plt

# Accuracy values
models = ["Our Model", "U-Net", "ResNet", "FNO", "PR-CNN"]
accuracy = [97.14, 82.86, 82.86, 45.71, 88.57]

plt.figure(figsize=(8,6))
plt.plot(models, accuracy, marker="o", linestyle="-", color="tab:blue", linewidth=2)

# Annotate points
for m, acc in zip(models, accuracy):
    plt.text(m, acc+1, f"{acc:.2f}%", ha="center", fontsize=9)

plt.ylim(0, 100)
plt.ylabel("Accuracy (%)")
plt.title("Comparative Accuracy of Models")
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.show()



import matplotlib.pyplot as plt
import numpy as np

# Models and accuracies
models = ["Our Model", "U-Net", "ResNet", "FNO", "PR-CNN"]
accuracy = [97.14, 82.86, 82.86, 45.71, 88.57]

# Approximate inference times (smaller = faster)
inference_time = [0.06, 0.20, 0.18, 0.25, 0.22]

# Normalize inference time for color intensity (faster = darker)
norm_speed = (np.max(inference_time) - np.array(inference_time)) / (np.max(inference_time) - np.min(inference_time))

plt.figure(figsize=(10,6))

# Horizontal bars
bars = plt.barh(models, accuracy, color=plt.cm.Blues(norm_speed))

# Annotate bars with accuracy values
for bar, acc in zip(bars, accuracy):
    plt.text(bar.get_width() + 1, bar.get_y() + bar.get_height()/2, f"{acc:.2f}%", va='center', fontsize=10)

plt.xlabel("Accuracy (%)", fontsize=12)
plt.title("Comparative Accuracy and Relative Speed of Models", fontsize=14, fontweight='bold')
plt.xlim(0, 105)
plt.grid(axis="x", linestyle="--", alpha=0.5)

# Legend for speed intensity
from matplotlib.patches import Patch
legend_elements = [Patch(facecolor=plt.cm.Blues(1.0), label='Fastest'),
                   Patch(facecolor=plt.cm.Blues(0.0), label='Slowest')]
plt.legend(handles=legend_elements, title="Relative Speed", loc="lower right")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Models and accuracies
models = ["Our Model", "U-Net", "ResNet", "FNO", "PR-CNN"]
accuracy = [97.14, 82.86, 82.86, 45.71, 88.57]

# Approximate inference times (smaller = faster)
inference_time = [0.06, 0.20, 0.18, 0.25, 0.22]

plt.figure(figsize=(10,6))

# Plot points
for i, model in enumerate(models):
    if model == "Our Model":
        plt.scatter(inference_time[i], accuracy[i], s=200, marker='*', color='tab:red', label=model)
    else:
        plt.scatter(inference_time[i], accuracy[i], s=120, marker='o', color='tab:blue')
    plt.text(inference_time[i]+0.005, accuracy[i]+0.5, model, fontsize=10, fontweight='bold')

plt.xlabel("Inference Time (sec per case) ↓ faster", fontsize=12)
plt.ylabel("Accuracy (%) ↑ higher", fontsize=12)
plt.title("Speed vs Accuracy Tradeoff of Models", fontsize=14, fontweight='bold')
plt.grid(True, linestyle='--', alpha=0.5)
plt.xlim(0, max(inference_time)+0.05)
plt.ylim(40, 100)

plt.tight_layout()
plt.show()